### ISSUE TITLE
Int lib reliability

### ISSUE THREAD

**Issue by henry-hz** [Consensys/WrappedEther.dfy#15]
When testing the Int lib, I got an unexpected type violation:
```dafny

include "../../lib/evm-dafny/src/dafny/util/int.dfy"
include "../../lib/evm-dafny/libs/DafnyCrypto/src/dafny/util/math.dfy"



module Try {

    import opened Int
    import MathUtils

        function Calc(n: u256, c: u256) : u256
        requires c <= 1_000
        requires n <= 1_000 {
            c * n
        }

}
```

got
```bash
src/core/d.dfy(16,14): Error: result of operation might violate newtype constraint for 'u256'
   |
16 |             c * n
   |               ^


Dafny program verifier finished with 0 verified, 1 error
```

**Comment by henry-hz** [comment]
Found that to sum using the Int lib we need a function like this one:
```dafny
module DSMath {
    import opened Int

    function Add(x: u256, y: u256) : (z: u256) {
        var lhs := x as int;
        var rhs := y as int;
        var res := (lhs + rhs) % TWO_256;
        res as u256
    }
}
```

**Comment by DavePearce** [comment]
Your original function `Calc` looked OK to me.  Dafny, unfortunately, can struggle with things like this.  I had a similar [problem myself](https://github.com/dafny-lang/dafny/issues/4071).  We generatelly run with the `--disable-nonlinear-arithmetic` flag enabled in order for Dafny to work better with bytecode contracts (e.g. the WrappedEther contract), but this causes its own problems.
