### ISSUE TITLE
Update Proof to check for Underflow / Overflow

### ISSUE THREAD

**Issue by DavePearce** [Consensys/WrappedEther.dfy#23]
Some comments

* (`And`) It would be good to automatically generate the various instantiations of `And`, such as `AndU160`, etc.

**Comment by DavePearce** [comment]
## Status

- `allowance` (0 errors)
- `approve` **(1 error)**
- `balanceOf` (0 errors)
- `decimals` **(1 errors)**
- `deposit` (0 errors)
- `name` **(27 errors)**
- `symbol` **(27 errors)**
- `totalSupply` (0 errors)
- `transfer` (0 errors)
- `util` **(17 errors)**

**Comment by DavePearce** [comment]
So, an interesting and important problem raised in `approve`:

1. `MStore` Writing when the address is unknown invalidates the free memory pointer which is a precondition for every block.  _Therefore, I think the address being written should always be a dependency._
2. 'AndU160` If the `Push 0xfff...` and `AndU160` fall on a block boundary, then we need a precondition about `Peek(0) == 0xfff...`.
3. Assumptions now have to be marked `{:axiom}`.
4. Need to figure out how to split up the remainder.

Is it possible this is arising from the known constants held in storage?  If so, then there is something we could do here.

**Comment by DavePearce** [comment]
I think another take away is that code which manipulates the free memory pointer is not well handled.  For example, in `name` we need to add various things that somehow bound what is known about the free memory pointer.

**Comment by henry-hz** [comment]
A very strange result I got when playing with fixed point math, multipling 10^18 * 10^18, i.e. wad * wad, I got a 10^34 ...  In lean4 I get a good 10^36 result.

```
include "number.dfy"
include "maps.dfy"
include "tx.dfy"



// Fixed point arithmetic math
// https://github.com/dapphub/ds-math/blob/master/src/math.sol
module Fixed {

import opened Number
import opened Maps
import opened Tx

    const WAD: u256 := 1000000000000000000
    const RAY: u256 := 1000000000000000000000000000

    function Add(x: u256, y: u256) : u256 
    requires (x as nat) + (y as nat) <= MAX_U256 as nat{
        x + y
    }

    function Sub(x: u256, y: u256) : u256
    requires (x as nat) - (y as nat) >= 0 as nat {
        x - y
    }

    function Mul(x: u256, y: u256) : u256
    requires (x as nat) * (y as nat) <= MAX_U256 as nat {
        x * y
    }

    function Wmul(x: u256, y: u256) : u256 
    requires y == 0 || (x as nat) * (y as nat) <= MAX_U256 as nat 
    requires Mul(x,y) as nat <= MAX_U256 {
        var m: u256 := Mul(x,y);
        var w: u256 := WAD / 2;
        assume {:axiom} (m as nat) + (w as nat) <= MAX_U256 as nat;
        (Add(m , w))/WAD
    }

}

// --- TESTS

import opened Fixed
import opened Number
import opened Maps
import opened Tx

method {:test} testFindMax() {
    var j := 10000000000000000000 as u256;
    var i := 10000000000000000000 as u256;
    var r := 10000000000000000000 as u256;
    assert Wmul(j,i) == r; // does not pass!

    var x : nat := 100000000000000000;
    // 10^18 * 10^18 = 10^36
    print(x*x); // it has 34 zeros ! help
}
```

**Comment by henry-hz** [comment]
Seems that the issue is on the `print` function. Anyway, I am getting a precision error when using the `Wmul` function, see that I added a zero on the `r`, but doing only with `nat` it just works:
```dafny
method {:test} testFindMax() {
    var j := 10000000000000000000 as u256;
    var i := 10000000000000000000 as u256;
    var r := 100000000000000000000 as u256;
    assert Wmul(j,i) == r; // pass only adding a '0'

    var x : nat := 100000000000000000;
    // 10^18 * 10^18 = 10^36
    //print(x*x); // it has 34 zeros ! help

    var x1 : nat := 1000000000000000000;
    var x2 : nat := 1000000000000000000;
    var r1 : nat := 1000000000000000000000000000000000000;
    var r2 : nat := (r1 + (x1/2)) / x1;
    assert x1*x2 == r1;
    print(x1*x2);
    assert r2 == x1;
}
```
